In [60]:
import numpy as np
import random

In [3]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
a=np.eye(3)

In [10]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
np.linspace(1,100,12)

array([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91.,
       100.])

In [22]:
a=np.eye(3)
a[:,1]=[1,2,3]
a

array([[1., 1., 0.],
       [0., 2., 0.],
       [0., 3., 1.]])

In [32]:
np.random.seed(2)
np.random.rand(3,3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [47]:
np.random.seed(5)
np.random.randint(low=1, high=10,size=(3,3))

array([[4, 7, 7],
       [1, 9, 5],
       [8, 1, 1]])

In [67]:
a=np.arange(6)
b=np.arange(1,7)
print(a)
random.shuffle(b)
b

[0 1 2 3 4 5]


array([4, 5, 1, 2, 3, 6])

In [52]:
np.arange(6)>=2

array([False, False,  True,  True,  True,  True])

In [53]:
np.arange(6)>2

array([False, False, False,  True,  True,  True])

In [61]:
help(random.shuffle)

Help on method shuffle in module random:

shuffle(x) method of random.Random instance
    Shuffle list x in place, and return None.



In [72]:
b[b>=a]

array([4, 5, 6])

In [78]:
I=np.eye(3)
B=I+68*np.random.rand(3,3)

In [79]:
A=10*np.random.rand(3,3)

In [80]:
(I+A)@B

array([[ 83.09281429,   1.07639948, 336.57998961],
       [ 81.97181568,  28.79994562,  36.03989827],
       [381.90317795, 461.4168987 ,  26.17676792]])